[package]
name = "magpie"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "magpie_lib"
path = "src/lib.rs"

[dependencies]
config = "0.13.3"
lofty = "0.15.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_with = "3.0.0"
tokio = { version = "1.26.0", features = ["full"] }
walkdir = "2.3.3"
thiserror = "1.0"
clap = { version = "4.3.12", features = ["derive"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio", "tls-rustls", "postgres", "migrate"]}
