[package]
name = "magpie_types"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
strum = "0.25.0"
strum_macros = "0.25.2"
