[application]
name = "swoop"
default_platform = "web"
out_dir = "../dist"
asset_dir = "public/"

[web.app]
title = "swoop"
base_path = "web"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]
index_on_404 = true

[web.resource]
style = [
    "./assets/style.css",
]

script = []

[web.resource.dev]
style = [
    "../assets/style.css",
]
script = []
